spring:
  datasource:
    url: jdbc:postgresql://ec2-54-228-32-29.eu-west-1.compute.amazonaws.com:5432/d2gjhpssa495rg
    driverClassName: org.postgresql.Driver
    database-platform: postgres
    username: zeupouvdsmqxel
    password: 5d1dc7a6938edcf7e516be3a2ff2d8b9dbd643f6820a93eed4594715c0b4c6d5
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    #hibernate.ddl-auto: create
    show-sql: true